# Trading Strategies Configuration
# Always buy nearest strike price OTM and nearest DTE.
# Sell half the position at each profit target and exit fully if any stop loss triggers.

strategies:
  spy_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "SPY"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 1.00  # Sell half of the position after a $1 move
        - 2.00  # Sell the remaining half after a $2 move

  spx_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "SPX"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 15.00  # Sell half of the position after a $15 move
        - 30.00  # Sell the remaining half after a $30 move

  qqq_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "QQQ"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 1.00  # Sell half of the position after a $1 move
        - 2.00  # Sell the remaining half after a $2 move

  nvda_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "NVDA"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 0.50  # Sell half of the position after a $0.50 move
        - 1.00  # Sell the remaining half after a $1 move

  tsla_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "TSLA"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 2  # Sell half of the position after a $2 move
        - 4  # Sell the remaining half after a $4 move

  amzn_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "AMZN"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 1.00  # Sell half of the position after a $1 move
        - 2.00  # Sell the remaining half after a $2 move

  iwm_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "IWM"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 0.50  # Sell half of the position after a $0.50 move
        - 1.00  # Sell the remaining half after a $1 move

  spy_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      ticker: "SPY"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 1.00  # Sell half of the position after a $1 move
        - 2.00  # Sell the remaining half after a $2 move

  spx_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      ticker: "SPX"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 15.00  # Sell half of the position after a $15 move
        - 30.00  # Sell the remaining half after a $30 move

  qqq_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      ticker: "QQQ"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 1.00  # Sell half of the position after a $1 move
        - 2.00  # Sell the remaining half after a $2 move

  nvda_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:    
      ticker: "NVDA"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 0.50  # Sell half of the position after a $0.50 move
        - 1.00  # Sell the remaining half after a $1 move

  tsla_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      ticker: "TSLA"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 2  # Sell half of the position after a $2 move
        - 4  # Sell the remaining half after a $4 move

  amzn_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
     ticker: "AMZN"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 1.00  # Sell half of the position after a $1 move
        - 2.00  # Sell the remaining half after a $2 move

  iwm_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      icker: "IWM"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 0.50  # Sell half of the position after a $0.50 move
        - 1.00  # Sell the remaining half after a $1 move

  spy_bosk:
    enabled: true
    script: "spy_bosk_strategy.py"
    args:
      ticker: "SPY"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 1.00  # Sell half of the position after a $1 move
        - 2.00  # Sell the remaining half after a $2 move

  spx_bosk:
    enabled: true
    script: "spy_bosk_strategy.py"
    args:
      ticker: "SPX"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 15.00  # Sell half of the position after a $15 move
        - 30.00  # Sell the remaining half after a $30 move

  qqq_bosk:
    enabled: true
    script: "spy_bosk_strategy.py"
    args:
      ticker: "QQQ"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 1.00  # Sell half of the position after a $1 move
        - 2.00  # Sell the remaining half after a $2 move

  nvda_bosk:
    enabled: true
    script: "spy_bosk_strategy.py"
    args:
      ticker: "NVDA"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 0.50  # Sell half of the position after a $0.50 move
        - 1.00  # Sell the remaining half after a $1 move

  tsla_bosk:
    enabled: true
    script: "spy_bosk_strategy.py"
    args:
      ticker: "TSLA"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 2  # Sell half of the position after a $2 move
        - 4  # Sell the remaining half after a $4 move

  amzn_bosk:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      ticker: "AMZN"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 1.00  # Sell half of the position after a $1 move
        - 2.00  # Sell the remaining half after a $2 move

  iwm_bosk:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      icker: "IWM"
      contracts: 2
      paper_trading: true
      port: 7497
      partial_sell_targets:
        - 0.50  # Sell half of the position after a $0.50 move
        - 1.00  # Sell the remaining half after a $1 move

# Global settings
global:
  log_level: "INFO"
  max_retries: 3
  restart_on_failure: true
