# Trading Strategies Configuration
# Always buy nearest strike price OTM and nearest DTE.
# Sell half the position at each profit target and exit fully if any stop loss triggers.

strategies:
  spy_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "SPY"
      contracts: 2
      underlying_move_target: 1.00  
      itm_offset: 2.00              
      paper_trading: true
      port: 7497

  spx_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "SPX"
      contracts: 2
      underlying_move_target: 15.00  
      itm_offset: 30.00            
      paper_trading: true
      port: 7497

  qqq_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "QQQ"
      contracts: 2
      underlying_move_target: 1.00  
      itm_offset: 2.00  
      paper_trading: true
      port: 7497

  nvda_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "NVDA"
      contracts: 2
      underlying_move_target: 0.50  
      itm_offset: 1.00   
      paper_trading: true
      port: 7497

  tsla_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "TSLA"
      contracts: 2
      underlying_move_target: 2.00  
      itm_offset: 4.00               
      paper_trading: true
      port: 7497

  amzn_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "AMZN"
      contracts: 2
      underlying_move_target: 1.00  
      itm_offset: 2.00    
      paper_trading: true
      port: 7497

  iwm_orb:
    enabled: true
    script: "spy_orb_strategy.py"
    args:
      ticker: "IWM"
      contracts: 2
      underlying_move_target: 0.50  
      itm_offset: 1.00   
      paper_trading: true
      port: 7497

  spy_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      ticker: "SPY"
      contracts: 2
      underlying_move_target: 1.00  
      itm_offset: 2.00               
      paper_trading: true
      rsi_threshold: 0.01 # this number is subtracted from oversold, added to overbought. (so for this case, it would be 29.99 oversold, 70.01 overbought)
      ema_threshold: 0.01 # this number is subtracted from short setup, added to long setup. (so for this case, it would be 9.01 long, 8.99 short)
      port: 7497

  spx_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      ticker: "SPX"
      contracts: 2
      underlying_move_target: 15.00  
      itm_offset: 30.00               
      paper_trading: true
      port: 7497

  qqq_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      ticker: "QQQ"
      contracts: 2
      underlying_move_target: 1.00  
      itm_offset: 2.00   
      paper_trading: true
      port: 7497

  tsla_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      ticker: "TSLA"
      contracts: 2
      underlying_move_target: 2.00  
      itm_offset: 4.00  
      paper_trading: true
      port: 7497

  iwm_rev:
    enabled: true
    script: "spy_rev_strategy.py"
    args:
      ticker: "IWM"
      contracts: 2
      underlying_move_target: 0.50  
      itm_offset: 1.00  
      paper_trading: true
      port: 7497

# Global settings
global:
  log_level: "INFO"
  max_retries: 3
  restart_on_failure: true
  
