name: Build and Run macOS App (py2app)

on:
  push:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Build .app with py2app
        run: |
          rm -rf ./build ./dist ./venv_x86 *.egg-info
          pip install -r requirements.txt
          pip install py2app
          python setup.py clean --all
          python setup.py py2app --no-strip

      - name: Copy config.yaml to app bundle
        run: |
          cp config.yaml ./dist/MacApp.app/Contents/Resources/

      - name: Explore app bundle structure
        run: |
          echo "=== App bundle structure ==="
          find ./dist/MacApp.app -type d -name "*site*" -o -name "*package*" -o -name "*lib*" | head -20
          echo ""
          echo "=== Contents directory ==="
          ls -la ./dist/MacApp.app/Contents/
          echo ""
          echo "=== Resources directory ==="
          ls -la ./dist/MacApp.app/Contents/Resources/ | head -20
          echo ""
          echo "=== Looking for pandas ==="
          find ./dist/MacApp.app -name "*pandas*" -type d | head -10

      - name: Test Python module imports
        run: |
          # Create a simple test script
          cat > test_imports.py << 'EOF'
          import sys
          print("Python executable:", sys.executable)
          print("Python version:", sys.version)
          print("sys.path:")
          for p in sys.path:
              print(f"  {p}")
          print()
          
          try:
              import pandas as pd
              print("SUCCESS: pandas imported successfully")
              print("pandas location:", pd.__file__)
          except ImportError as e:
              print("ERROR importing pandas:", e)
          
          try:
              import numpy as np
              print("SUCCESS: numpy imported successfully")
              print("numpy location:", np.__file__)
          except ImportError as e:
              print("ERROR importing numpy:", e)
          EOF
          
          # Copy it to the app bundle
          cp test_imports.py ./dist/MacApp.app/Contents/Resources/
          
          # Run the test with the bundled Python
          echo "=== Testing with bundled Python ==="
          ./dist/MacApp.app/Contents/MacOS/python ./dist/MacApp.app/Contents/Resources/test_imports.py

      - name: Upload .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: MacApp
          path: dist/*.app

      - name: Run the app's binary
        run: |
          chmod +x ./dist/MacApp.app/Contents/MacOS/MacApp
          ./dist/MacApp.app/Contents/MacOS/MacApp > output.log 2>&1

      - name: Upload output log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-output
          path: output.log
      
